"""empty message

Revision ID: 043a30762e38
Revises: 52dfaeacddcb
Create Date: 2021-06-29 20:00:47.942784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043a30762e38'
down_revision = '52dfaeacddcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('looking_for_talent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'looking_for_talent')
    # ### end Alembic commands ###
