"""empty message

Revision ID: 0ba67872b23c
Revises: b79630e763a9
Create Date: 2021-06-27 13:52:35.973948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import false


# revision identifiers, used by Alembic.
revision = '0ba67872b23c'
down_revision = 'b79630e763a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))

   # op.drop_column('Venue','seeking_talent')

    # ### end Alembic commands ###
def downgrade():
    op.drop_column('Venue','seeking_talent')
    # ### end Alembic commands ###
