"""empty message

Revision ID: 290b126a314e
Revises: ffa81df33f78
Create Date: 2021-07-04 14:51:50.029334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290b126a314e'
down_revision = 'ffa81df33f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
