"""empty message

Revision ID: 588f1ab9bf5f
Revises: eb6da4113767
Create Date: 2021-06-27 13:27:33.455136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588f1ab9bf5f'
down_revision = 'eb6da4113767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('show_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Artist', 'shows', ['show_id'], ['id'])
    op.add_column('Venue', sa.Column('show_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'shows', ['show_id'], ['id'])
    op.drop_constraint('shows_artist_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_venue_id_fkey', 'shows', type_='foreignkey')
    op.drop_column('shows', 'venue_id')
    op.drop_column('shows', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('shows_venue_id_fkey', 'shows', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key('shows_artist_id_fkey', 'shows', 'Artist', ['artist_id'], ['id'])
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'show_id')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'show_id')
    # ### end Alembic commands ###
