"""empty message

Revision ID: 806a94ca55da
Revises: c2ba6cd26e6e
Create Date: 2021-06-26 22:05:39.396885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806a94ca55da'
down_revision = 'c2ba6cd26e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('looking_for_venues', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('looking_for_talent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'looking_for_talent')
    op.drop_column('Artist', 'looking_for_venues')
    # ### end Alembic commands ###
