"""empty message

Revision ID: 9006332285d2
Revises: e98ee7557059
Create Date: 2021-07-04 13:13:40.102030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9006332285d2'
down_revision = 'e98ee7557059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'deleted')
    # ### end Alembic commands ###
