"""empty message

Revision ID: b79630e763a9
Revises: 588f1ab9bf5f
Create Date: 2021-06-27 13:49:18.006552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79630e763a9'
down_revision = '588f1ab9bf5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
