"""empty message

Revision ID: b87d8615459c
Revises: 4c7b1e1bdcab
Create Date: 2021-06-29 14:00:42.159140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87d8615459c'
down_revision = '4c7b1e1bdcab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
